### ISSUE TITLE
Add bunkers

### ISSUE THREAD

**Issue by ghermans** [FiveM-Scripts/fs_freemode#13]
- [x] Add needed IPLs
- [x] Add interior inside the bunker
- [x] Add Pedestrians to the bunker
- [x] Add vehicles
- [ ] Add invite system
- [x] Make players unable to jump
------------webapp----------------
-------"disruption logistics"-------
- [x] Add app
- [x] Add research
- [x] Add bunker stats
- [x] Make buttons work
- [ ] Save/Load bunker stats to/from DB things like stock level, current upgrades, staff assignments, etc
- [ ] Create missions like steal supplies and deliver finished product etc
- [ ] Add ability to "Buy" the upgrades
- [ ] Add % chance that the cops will raid you depending on security upgrade status

**Comment by davedumas0** [comment]
still need to get the player to NOT be able to jump and add the ability to allow players to "invite" other players into the bunkers and sync with the inviting players "stuff"
