### ISSUE TITLE
Access denied for command add_principal

### ISSUE THREAD

**Issue by lukasgolson** [FiveM-Scripts/fs_freemode#24]
`Connecting: AquaDark
Sending heartbeat to live-internal.fivem.net:30110
Access denied for command add_principal.
Error running system event handling function for resource fs_freemode: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: libs/db.lua:31: attempt to index a nil value (field 'docs')
stack traceback:
        libs/db.lua:31: in local 'userCallback'
        citizen:/scripting/lua/scheduler.lua:260: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>`

Happens when I join the game!

Scripts:
sessionmanager
mapmanager
chat
spawnmanager
hardcap
rconlog
loadingscreen
essentialmode
es_admin2
fs_freemode
fs_freemode

**Comment by ghermans** [comment]
It seems that your database is not created for fs_freemode, this can be caused if your document already exists in the essentialmode database.    

Try to remove your `essentialmode` database from [CouchDB](http://127.0.0.1:5984/_utils/#/_all_dbs).
Then restart your FXServer and verify that you have 2 databases.
![cdbsknipsel](https://user-images.githubusercontent.com/1594411/31053719-2dc42712-a6a4-11e7-975b-4fdd359a6b3d.PNG)

**Comment by lukasgolson** [comment]
Both databases appear, however I am only getting this error now:
`Access denied for command add_principal.
[{"locked":false},{"locked":false},{"locked":false},{"locked":false}]`

**Comment by ghermans** [comment]
That error has nothing todo with fs_freemode.

Go to the [FiveM wiki](https://wiki.fivem.net/wiki/Running_FXServer),  there you will find an example on how to allow commands on your server.

**Comment by lukasgolson** [comment]
Ok thanks! I thought it was freemode since the logs were pointing towards freemode and it never appeared when I had it uninstalled....

Its probably essential mode, Thanks!
