### ISSUE TITLE
fs_freemode Disables AI & Vehicle Spawning

### ISSUE THREAD

**Issue by DevRain2500** [FiveM-Scripts/fs_freemode#42]
I am not sure if this is intended or not but this script seems to disable AI on my server. If it is intended, is there a way to turn the AI back on? I can't find anything about it in the script files. (it also disables spawning of vehicles via trainer)

I have tried the following:
- Restarting script.
- Reinstalling script.

When I start the server without the script, the AI loads fine and I can spawn vehicles. But as soon as I activate the script, the AI and vehicle spawning is disabled.

**Comment by ghermans** [comment]
I have just verified this with a clean setup and can't reproduce the reported issues, check the screenshots below.

#### Some questions

1. Can you verify if you have the same issue with the [latest version](https://github.com/FiveM-Scripts/fs_freemode/releases/latest) **v1.2.3**.
2. Do all people have the same issue on your server or only you?
3. What other resources are you loading ?
4. What is the platform that your server is running on (windows, linux) ?


### Peds
![20171116174638_1](https://user-images.githubusercontent.com/1594411/32903786-37d2475e-caf6-11e7-82ed-8d6b23e0c4d7.jpg)

### Vehicle spawn
![20171116175529_1](https://user-images.githubusercontent.com/1594411/32904299-61fe9e0a-caf7-11e7-8e54-333cb1ae63f0.jpg)

**Comment by ghermans** [comment]
additional question: can you provide a list of all resources that you are loading?

**Comment by DevRain2500** [comment]
Some Answers:
1. This issue also happens with the [latest version you linked](https://github.com/FiveM-Scripts/fs_freemode/releases/latest).
2. Yes, I have tested it with one other person and they have the same issue.
3. From server.cfg:
```cfg
...
# EssentialMode database settings
set es_couchdb_url "127.0.0.1"
set es_couchdb_port "5984"
set es_couchdb_password "user:pass"

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start playernames

# Starting Custom Plugins
#start FiveM-Material_Load-Loading-Screen
start essentialmode
start es_admin2
start fs_freemode
#start five-race
#start wk_actionmenu
#start acl
#start runcode
...
# add system admins
add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit
add_principal identifier.steam:<redacted> group.admin # add the admin to the group
add_ace resource.essentialmode command.add_ace allow
add_ace resource.essentialmode command.add_principal allow
```
(Other plugins commented out for troubleshooting)
4. Windows Server 2016 64-Bit on a VPS.

Question for you: I am using an older version of FX Server because I can not get newer versions to run properly. What version of FX Server are you running?

**Comment by ghermans** [comment]
Hmm the fact that you are having those issues on a windows server seems strange, i actually expected that behavior on a linux server instead.

Just to be sure i asked one of our team members to verify if he had any issues with the latest fs_freemode version however he also could not reproduce the issues.

#### The FX-Server versions that i am using:
| Version | Operating system |
| ------- |------------------- |
| [401-7da138fa4851430482ff2fb4e196b871d5ea3efb](https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/401-7da138fa4851430482ff2fb4e196b871d5ea3efb/) | Linux (ubuntu) |
| [405-34390097139cb003df3d592bfdab963af5264ea8](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/405-34390097139cb003df3d592bfdab963af5264ea8/) | Windows |

#### Small suggestion

Try to upgrade to a newer fx-server version and try it with these basic resources.
```
add_ace resource.essentialmode command.add_ace allow
add_ace resource.essentialmode command.add_principal allow

start mapmanager
start chat
start spawnmanager
start sessionmanager
start hardcap
start rconlog
start essentialmode
start es_admin2
start fs_freemode
````

**Comment by DevRain2500** [comment]
Ok this is going to sound really weird, but I had to upgrade the server version from the beginning skipping 10 versions until I got to 405 in order for the server to even start... (would give "Failed to create environment" error).

I am going to test the AI/vehicles now that I got it working in the first place.

**Comment by DevRain2500** [comment]
Still no AI/spawning vehicles after upgrading to fx-server version 405. 
![november-16-2017_358](https://user-images.githubusercontent.com/11688685/32924366-4722ef4c-cb0a-11e7-9a61-f90f5385b7cb.jpg)

**Comment by ghermans** [comment]
Maybe a stupid question but did you tried to clear your server cache files?

**Comment by DevRain2500** [comment]
Doing a completely fresh install seems to have fixed the issue. I feel really stupid now... Thanks very much for your help.
(and yes I did clear the cache :P )
