### ISSUE TITLE
[MariaDB] table creation issue

### ISSUE THREAD

**Issue by driftonez** [FiveM-Scripts/fs_freemode#47]
im receiving this problem and im unsure what to do. i thought id ask before i muck around and break something.

[ERROR] [MySQL] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS fs_freemode (identifier varchar(255), weapons json DEFAULT NULL) {=}": You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json DEFAULT NULL)' at line 1

ive tried to creat a new table as it didnt exist but unsure what do do once ive done that, sorry still learning MySQL

**Comment by ghermans** [comment]
Could you try to use the default mysql-server (https://dev.mysql.com/downloads/mysql) and see if that works because i didn't verified if it works on MariaDB.

**Comment by ghermans** [comment]
This should be resolved with the latest release, please report if you still experience this issue.
