### ISSUE TITLE
Invisible cars

### ISSUE THREAD

**Issue by amerem3** [FiveM-Scripts/fs_freemode#55]
Owned cars that are spawned in are invisible for other players

**Comment by ghermans** [comment]
Do you mean that vehicles are not displayed to other users when you spawn the vehicle from the inventory or after you purchased the vehicle from the shop?

To reproduce this issue could you explain what steps you did to spawn the vehicle ?

**Comment by amerem3** [comment]
I hit the Y button on my controller after I bought an Albany Hermes from the dealership and hit the A button to spawn it in, I can get in it and drive around just fine but for my friend the car is not there and instead I am in the ground. He can also shoot me and I take the bullet not the car.

**Comment by ghermans** [comment]
Could you please verify if the fix in the [hotfix](https://github.com/FiveM-Scripts/fs_freemode/tree/hotfix) branch resolved the issue for you?

**Comment by amerem3** [comment]
I will test it

**Comment by amerem3** [comment]
It fixed the invisible car problem
