### ISSUE TITLE
Blips

### ISSUE THREAD

**Issue by amerem3** [FiveM-Scripts/fs_freemode#57]
The Fs freemode blips don't have names.....

**Comment by ghermans** [comment]
i guess you changed something since i did 2 clean installs the last 2hours and didn't had any issues.
Check your client console for any errors (F8).

**Comment by amerem3** [comment]
Testing a fresh install of it now

**Comment by amerem3** [comment]
no still broken https://imgur.com/a/j3hQJ

**Comment by amerem3** [comment]
I had no errors as well I just looked over everything

**Comment by ghermans** [comment]
This must be a client issue , as i could not reproduce the issue.

**Comment by amerem3** [comment]
Were you testing it with just FS freemode? I had read the other day that to many blips from alot of mods will break the map.
