### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MrRedNeckKYN** [FiveM-Scripts/fs_freemode#59]
I just start the server and get this error???

Error running system event handling function for resource fs_freemode: citizen:/
scripting/lua/scheduler.lua:41: Failed to execute thread: server.lua:109: attemp
t to index a boolean value (local 'freemodeuser')
stack traceback:
        server.lua:109: in upvalue 'callback'
        libs/db.lua:62: in local 'userCallback'
        citizen:/scripting/lua/scheduler.lua:274: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scriptin
g/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scriptin
g/lua/scheduler.lua:138>

**Comment by ghermans** [comment]
This means that the script can't connect to your CouchDB server.
Verify the settings in your server.cfg and make sure CouchDB is running.

**Comment by MrRedNeckKYN** [comment]
fixed it
