### ISSUE TITLE
Ability to disable random spawning of vehicles via F9?

### ISSUE THREAD

**Issue by nightimegames** [FiveM-Scripts/fs_freemode#64]
This can cause problems with RP, especially since an escaping criminal could unrealistically switch cars in an instant. Designating a "Garage" or such would prevent this issue.

**Comment by OhTanoshi** [comment]
I could be wrong but i belive this is being replaced with the c# game mode tarantula-freemode

**Comment by pongo1231** [comment]
Not directly "replaced". It's just a different freemode gamemode trying to bring a GTA:O like experience to FiveM. It's currently only being developed by me in my free time.
